image: gitpod/workspace-base

tasks:

- name: install mamba
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n BioDivBUSCO -c conda-forge -c bioconda busco=5.5.0 -y
    mamba clean --all -y
- name: activate mamba
  command: |
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate BioDivBUSCO
    export PATH=/workspace/bin:"$PATH"
    cd /workspace/BioDivBUSCO/

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
