image: gitpod/workspace-base

tasks:
- name: install mamba and tools for BGA23 workshop
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n BioDivBUSCO -c conda-forge -c bioconda busco=5.5.0 -y

    mamba clean --all -y

    mamba activate BioDivBUSCO

  command: |
    /workspace/conda/bin/mamba init bash
    source ~/.bashrc
    mamba activate BioDivBUSCO
    cd /workspace/busco/

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
